In [1]:
%cd aws-BDA/data/

/home/jovyan/work/aws-BDA/data

In [2]:
import boto3

try:
    s3 = boto3.client("s3")
    buckets = s3.list_buckets()
    print("Conexion exitosa")
    print(f"Tienes {len(buckets['Buckets'])} en tu cuenta")
except Exception as e:
    print("Error de conexion")

Conexion exitosa
Tienes 2 en tu cuenta

# A. Catálogo de playas (CSV)

In [6]:
import pandas as pd
import requests
import json

# Catalogo Playas
catalogoPlayas = pd.read_csv("playas.csv")
catalogoPlayas = catalogoPlayas[["Nombre", "Provincia", "Término_M", "Duchas", "Aseos", "Acceso_dis", "Bandera_az", "Longitud", "X", "Y", "Grado_ocup", "Grado_urba"]]
catalogoPlayas

#Codigos Playas
codigo_playas = pd.read_csv("Playas_codigos.csv", sep=";", encoding="Latin-1")
dfCodigos = codigo_playas.head(10)
dfCodigos

,ID_PLAYA,NOMBRE_PLAYA,ID_PROVINCIA,NOMBRE_PROVINCIA,ID_MUNICIPIO,NOMBRE_MUNICIPIO,LATITUD,LONGITUD
0,301101,Raco de l'Albir,3,Alacant/Alicante,3011,l'Alfàs del Pi,"38º 34' 31""","-00º 03' 52"""
1,301401,Sant Joan / San Juan,3,Alacant/Alicante,3014,Alicante/Alacant,"38º 22' 48""","-00º 24' 32"""
2,301408,El Postiguet,3,Alacant/Alicante,3014,Alicante/Alacant,"38º 20' 46""","-00º 28' 38"""
3,301410,Saladar,3,Alacant/Alicante,3014,Alicante/Alacant,"38º 17' 02""","-00º 31' 08"""
4,301808,La Roda,3,Alacant/Alicante,3018,Altea,"38º 36' 29""","-00º 02' 16"""
5,301809,Cap Blanch,3,Alacant/Alicante,3018,Altea,"38º 35' 36""","-00º 03' 10"""
6,303102,Llevant / Playa de Levante,3,Alacant/Alicante,3031,Benidorm,"38º 32' 12""","-00º 07' 05"""
7,303104,Ponent / Playa de Poniente,3,Alacant/Alicante,3031,Benidorm,"38º 32' 14""","-00º 08' 55"""
8,304105,Cala Fustera,3,Alacant/Alicante,3041,Benissa,"38º 39' 53""","0º 05' 16"""
9,304704,La Fossa,3,Alacant/Alicante,3047,Calp,"38º 38' 46""","0º 04' 24"""

# B. API AEMET OpenData

In [4]:
import requests

api_key = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJodS5ibGFuY29hbG9uc29AZ21haWwuY29tIiwianRpIjoiNzY2M2VjNzMtMTcwMi00ZjJiLWI1ZWItYmQ4NDBkYjhhYTU2IiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE3NzM5MTQ1MjIsInVzZXJJZCI6Ijc2NjNlYzczLTE3MDItNGYyYi1iNWViLWJkODQwZGI4YWE1NiIsInJvbGUiOiIifQ.tiNJCj8JerhOttICARjVvshUGb6ibmkKlQhmMGTAEPE"

headers = {
    'cache-control': "no-cache",
    'accept': 'application/json',
    'api_key': api_key
}

info_playas = []

for id_Playas in dfCodigos["ID_PLAYA"]:
    
    id_Playas = str(id_Playas).zfill(7)
    url = f"https://opendata.aemet.es/opendata/api/prediccion/especifica/playa/{id_Playas}"

    response = requests.get(url=url, headers=headers)

    if response.status_code == 200:
            res_json = response.json()
            print(res_json)

            datos = requests.get(res_json['datos'])
            if response.status_code == 200:
                datos_json = datos.json()
                info_playas.append(datos_json)
                
playas = []
for datos in info_playas:

    datos_playa = datos[0]['prediccion']['dia'][0]

    playa = {
        "Playa": datos[0]['nombre'],
        "Estado Cielo": datos_playa['estadoCielo']['descripcion1'],
        "Viento": datos_playa['viento']['descripcion1'],
        "Oleaje": datos_playa['oleaje']['descripcion1'],
        "Temperatura Maxima": datos_playa['tMaxima']['valor1'],
        "Sensacion Termica": datos_playa['sTermica']['descripcion1'],
        "Temperatura Agua": datos_playa['tAgua']['valor1'],
        "UV Maximo": datos_playa['uvMax']['valor1'],
        "Fecha": pd.to_datetime(datos_playa['fecha'], format='%Y%m%d')
    }

    playas.append(playa)

df = pd.DataFrame(playas)
df.to_json("prediccion.json", orient='records')
df

{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/b8bd6506', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/0e447e6c', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/08aa59a1', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/7933a2d4', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/75cc7fb6', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/87840cf5', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/9f442260', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/95157636', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/fad367b3', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}
{'descripcion': 'exito', 'estado': 200, 'datos': 'https://opendata.aemet.es/opendata/sh/4096aca1', 'metadatos': 'https://opendata.aemet.es/opendata/sh/8ca2e7e3'}

,Playa,Estado Cielo,Viento,Oleaje,Temperatura Maxima,Sensacion Termica,Temperatura Agua,UV Maximo,Fecha
0,Raco de l'Albir,despejado,flojo,débil,20,suave,16,7,2026-04-15
1,Sant Joan / San Juan,despejado,flojo,débil,20,suave,17,7,2026-04-15
2,El Postiguet,despejado,flojo,débil,21,suave,17,7,2026-04-15
3,Saladar,despejado,flojo,débil,20,suave,18,7,2026-04-15
4,La Roda,despejado,flojo,débil,21,suave,16,7,2026-04-15
5,Cap Blanch,despejado,flojo,débil,21,suave,16,7,2026-04-15
6,Llevant / Playa de Levante,despejado,flojo,débil,19,suave,17,7,2026-04-15
7,Ponent / Playa de Poniente,despejado,flojo,débil,19,suave,17,7,2026-04-15
8,Cala Fustera,despejado,flojo,débil,20,suave,18,7,2026-04-15
9,La Fossa,despejado,flojo,débil,20,suave,18,7,2026-04-15

In [5]:
año = df['Fecha'].loc[1].year
mes = df['Fecha'].loc[1].month
dia = df['Fecha'].loc[1].day

s3.upload_file("playas.csv", "pr601-bronce-hugoblancoalonso", "bronce/catalogos/guia_playas/v1/playas.csv")
s3.upload_file("prediccion.json", "pr601-bronce-hugoblancoalonso", f"bronce/meteorologia/prediccion_playas/year={año}/month={mes}/day={dia}/prediccion.json")