In [1]:
import pandas as pd

In [2]:
# def convert(euros):
#     return int(euros)*0.90

# df = pd.read_csv(
#                 "datos.cdv", 
#                 converters = {"Salario_Anual": convert})

### CSV

In [ ]:
dfNorte = pd.read_csv("./UT03/ventas_norte.csv", sep=";")

dfNorte = dfNorte.rename(columns={
                            "ID_Transaccion": "id", 
                            "Fecha_Venta": "fecha", 
                            "Nom_Producto": "producto", 
                            "Cantidad_Vendida": "cantidad",
                            "Precio_Unit": "precio_unitario"
                            }
                        )
dfNorte["region"] = "Norte"
dfNorte.head()

FileNotFoundError: [Errno 2] No such file or directory: './UT03/data/ventas_norte.csv'

### XSLX

In [ ]:
dfSur = pd.read_excel("./UT03/ventas_sur.xlsx" , sheet_name=None)
dfSur = pd.concat(dfSur.values(), ignore_index=True)

dfSur = dfSur.rename(columns={
                            "SalesID": "id", 
                            "Date": "fecha", 
                            "Item": "producto", 
                            "Qty": "cantidad",
                            "UnitPrice": "precio_unitario"
                            }
                        )
dfSur["region"] = "Sur"
dfSur["fecha"] = dfSur["fecha"].astype(str)
dfSur["fecha"] = dfSur["fecha"].str.replace(" 00:00:00", "")
dfSur.head()

     id       fecha producto  cantidad  precio_unitario region
0  2000  2023-03-01  Monitor         6              624    Sur
1  2001  2023-03-04   Laptop         7              941    Sur
2  2002  2023-03-26    Mouse         3              989    Sur
3  2003  2023-02-01   Webcam         3              621    Sur
4  2004  2023-03-28    Mouse         5              437    Sur

### JSON

In [ ]:
import json

with open("./UT03/ventas_este.json", "r", encoding="utf-8") as f:
    data = json.load(f)
dfEste = pd.json_normalize(data, sep="_")
dfEste = dfEste.rename(columns={
                            "id_orden": "id", 
                            "timestamp": "fecha", 
                            "detalles_producto_nombre": "producto", 
                            "detalles_producto_specs_cantidad": "cantidad",
                            "detalles_producto_specs_precio": "precio_unitario"
                            }
                        )
dfEste["region"] = "Este"
dfEste = dfEste.drop(columns=["detalles_producto_categoria", "cliente_nombre", "cliente_email"], axis=1)
dfEste["id"] = dfEste["id"].str.replace("ORD-", "")
dfEste["fecha"] = dfEste["fecha"].str.replace(" 00:00:00", "")
dfEste.head()

     id       fecha producto  cantidad  precio_unitario region
0  3000  2023-03-09  Monitor         2              244   Este
1  3001  2023-01-20   Laptop         2              578   Este
2  3002  2023-01-01    Mouse         2              339   Este
3  3003  2023-02-07   Webcam         2              158   Este
4  3004  2023-03-18  Monitor         1              692   Este

### Consolidación

In [ ]:
dfTotal = pd.DataFrame()

dfs = [dfNorte, dfSur, dfEste]
dfTotal = pd.concat(dfs, ignore_index=True)

dfTotal.head()

     id       fecha producto  cantidad  precio_unitario region
0  1000  2023-02-21   Laptop         4              423  Norte
1  1001  2023-01-15   Laptop         2              171  Norte
2  1002  2023-03-13   Laptop         3               73  Norte
3  1003  2023-03-02  Teclado         1              139  Norte
4  1004  2023-01-21  Monitor         4              692  Norte

### Exportación Estandarizada

In [ ]:
dfTotal.to_csv("./UT03/ventas_consolidadas.csv", sep=",", encoding="utf-8", index=False)